### ISSUE TITLE
[PyLint] We need some exceptions!

### ISSUE THREAD

**Issue by EPgg92** [akb89/nima#27] opened 2017-05-08 22:31 UTC
We need the exceptions that we can import **from** if it a class.

we need exceptions for the file constance which can contains non-ASCII char
`Module nima.constance
W:  9, 0: Cannot decode using encoding "ASCII", unexpected byte at position 23 (invalid-encoded-data)`

We need {} to format str !

We don't understand some errors:
`Module nima.extraction.extractors.wikiextractor
E: 35, 0: invalid syntax (syntax-error)
`
`Module nima.generation.generators.word2vec
E: 20, 0: invalid syntax (syntax-error)
`

Have unused dependencies to be commented in preprocessing?  for now?

**Comment by akb89** [comment] 2017-05-11 08:21
@EPgg92 Should I close this issue?

**Comment by EPgg92** [comment] 2017-05-11 10:50
still the issue with `nima.extraction.extractors.wikiextractor` !
why don't remane our function nima_wikiextractor?

**Comment by akb89** [comment] 2017-05-11 13:38
I'm still looking for a clean alternative

**Comment by akb89** [comment] 2017-05-11 13:52
@EPgg92 I cannot reproduce the error with wikiextractor. Everything lints fine for me. 
I have: 
```
pylint 1.7.1
pydocstyle 2.0.0
pycodestyle 2.3.1
```

**Comment by akb89** [comment] 2017-05-11 20:31
Actually the error is related to the dependency not being properly installed on the system so this shouldn't affect the build as long as all the dependencies have been added to the setup.py install_requires.
I'm closing this issue.

**Closed by akb89** 2017-05-11 20:31 UTC
Labels: bug, help wanted, invalid
